import { SelectOption } from '@/components/ui/select'

export const countries: SelectOption[] = [
    { label: 'Nigeria', value: 'Nigeria' },
    { label: 'Ghana', value: 'Ghana' },
    { label: 'South Africa', value: 'South Africa' },
    { label: 'Kenya', value: 'Kenya' },
    { label: 'Tanzania', value: 'Tanzania' },
    { label: 'Uganda', value: 'Uganda' },
    { label: 'Cameroon', value: 'Cameroon' },
    { label: 'Egypt', value: 'Egypt' },
    { label: 'Ethiopia', value: 'Ethiopia' },
    { label: 'Rwanda', value: 'Rwanda' },
    { label: 'Senegal', value: 'Senegal' },
    { label: 'Côte d\'Ivoire', value: 'Côte d\'Ivoire' },
    { label: 'United Kingdom', value: 'United Kingdom' },
    { label: 'United States', value: 'United States' },
    { label: 'Canada', value: 'Canada' },
]

export const states: Record<string, SelectOption[]> = {
    Nigeria: [
        { label: 'Abia', value: 'Abia' },
        { label: 'Adamawa', value: 'Adamawa' },
        { label: 'Akwa Ibom', value: 'Akwa Ibom' },
        { label: 'Anambra', value: 'Anambra' },
        { label: 'Bauchi', value: 'Bauchi' },
        { label: 'Bayelsa', value: 'Bayelsa' },
        { label: 'Benue', value: 'Benue' },
        { label: 'Borno', value: 'Borno' },
        { label: 'Cross River', value: 'Cross River' },
        { label: 'Delta', value: 'Delta' },
        { label: 'Ebonyi', value: 'Ebonyi' },
        { label: 'Edo', value: 'Edo' },
        { label: 'Ekiti', value: 'Ekiti' },
        { label: 'Enugu', value: 'Enugu' },
        { label: 'FCT - Abuja', value: 'FCT - Abuja' },
        { label: 'Gombe', value: 'Gombe' },
        { label: 'Imo', value: 'Imo' },
        { label: 'Jigawa', value: 'Jigawa' },
        { label: 'Kaduna', value: 'Kaduna' },
        { label: 'Kano', value: 'Kano' },
        { label: 'Katsina', value: 'Katsina' },
        { label: 'Kebbi', value: 'Kebbi' },
        { label: 'Kogi', value: 'Kogi' },
        { label: 'Kwara', value: 'Kwara' },
        { label: 'Lagos', value: 'Lagos' },
        { label: 'Nasarawa', value: 'Nasarawa' },
        { label: 'Niger', value: 'Niger' },
        { label: 'Ogun', value: 'Ogun' },
        { label: 'Ondo', value: 'Ondo' },
        { label: 'Osun', value: 'Osun' },
        { label: 'Oyo', value: 'Oyo' },
        { label: 'Plateau', value: 'Plateau' },
        { label: 'Rivers', value: 'Rivers' },
        { label: 'Sokoto', value: 'Sokoto' },
        { label: 'Taraba', value: 'Taraba' },
        { label: 'Yobe', value: 'Yobe' },
        { label: 'Zamfara', value: 'Zamfara' },
    ],
    Ghana: [
        { label: 'Greater Accra', value: 'Greater Accra' },
        { label: 'Ashanti', value: 'Ashanti' },
        { label: 'Central', value: 'Central' },
        { label: 'Eastern', value: 'Eastern' },
        { label: 'Northern', value: 'Northern' },
        { label: 'Volta', value: 'Volta' },
        { label: 'Western', value: 'Western' },
    ],
    'South Africa': [
        { label: 'Eastern Cape', value: 'Eastern Cape' },
        { label: 'Free State', value: 'Free State' },
        { label: 'Gauteng', value: 'Gauteng' },
        { label: 'KwaZulu-Natal', value: 'KwaZulu-Natal' },
        { label: 'Limpopo', value: 'Limpopo' },
        { label: 'Mpumalanga', value: 'Mpumalanga' },
        { label: 'North West', value: 'North West' },
        { label: 'Northern Cape', value: 'Northern Cape' },
        { label: 'Western Cape', value: 'Western Cape' },
    ],
    Kenya: [
        { label: 'Nairobi', value: 'Nairobi' },
        { label: 'Mombasa', value: 'Mombasa' },
        { label: 'Kisumu', value: 'Kisumu' },
        { label: 'Nakuru', value: 'Nakuru' },
        { label: 'Kiambu', value: 'Kiambu' },
    ],
    Tanzania: [
        { label: 'Dar es Salaam', value: 'Dar es Salaam' },
        { label: 'Dodoma', value: 'Dodoma' },
        { label: 'Arusha', value: 'Arusha' },
        { label: 'Mwanza', value: 'Mwanza' },
    ],
    Uganda: [
        { label: 'Central', value: 'Central' },
        { label: 'Eastern', value: 'Eastern' },
        { label: 'Northern', value: 'Northern' },
        { label: 'Western', value: 'Western' },
    ],
    Cameroon: [
        { label: 'Centre', value: 'Centre' },
        { label: 'Littoral', value: 'Littoral' },
        { label: 'West', value: 'West' },
        { label: 'North West', value: 'North West' },
        { label: 'South West', value: 'South West' },
    ],
    Egypt: [
        { label: 'Cairo', value: 'Cairo' },
        { label: 'Alexandria', value: 'Alexandria' },
        { label: 'Giza', value: 'Giza' },
        { label: 'Luxor', value: 'Luxor' },
    ],
    Ethiopia: [
        { label: 'Addis Ababa', value: 'Addis Ababa' },
        { label: 'Oromia', value: 'Oromia' },
        { label: 'Amhara', value: 'Amhara' },
    ],
    Rwanda: [
        { label: 'Kigali', value: 'Kigali' },
        { label: 'Eastern', value: 'Eastern' },
        { label: 'Western', value: 'Western' },
        { label: 'Northern', value: 'Northern' },
        { label: 'Southern', value: 'Southern' },
    ],
    Senegal: [
        { label: 'Dakar', value: 'Dakar' },
        { label: 'Thiès', value: 'Thiès' },
        { label: 'Saint-Louis', value: 'Saint-Louis' },
    ],
    "Côte d'Ivoire": [
        { label: 'Abidjan', value: 'Abidjan' },
        { label: 'Yamoussoukro', value: 'Yamoussoukro' },
        { label: 'Bouaké', value: 'Bouaké' },
    ],
    'United Kingdom': [
        { label: 'England', value: 'England' },
        { label: 'Scotland', value: 'Scotland' },
        { label: 'Wales', value: 'Wales' },
        { label: 'Northern Ireland', value: 'Northern Ireland' },
    ],
    'United States': [
        { label: 'California', value: 'California' },
        { label: 'Florida', value: 'Florida' },
        { label: 'Georgia', value: 'Georgia' },
        { label: 'Illinois', value: 'Illinois' },
        { label: 'Maryland', value: 'Maryland' },
        { label: 'Massachusetts', value: 'Massachusetts' },
        { label: 'New Jersey', value: 'New Jersey' },
        { label: 'New York', value: 'New York' },
        { label: 'Texas', value: 'Texas' },
        { label: 'Washington', value: 'Washington' },
    ],
    Canada: [
        { label: 'Alberta', value: 'Alberta' },
        { label: 'British Columbia', value: 'British Columbia' },
        { label: 'Ontario', value: 'Ontario' },
        { label: 'Quebec', value: 'Quebec' },
        { label: 'Manitoba', value: 'Manitoba' },
    ],
}
